services:
  - type: web
    name: la-meublerie-backend
    env: docker
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: ./Back/Dockerfile
    dockerContext: ./Back
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: PORT
        value: "10000"
