services:
  - type: web
    name: la-meublerie-backend
    env: java
    plan: free
    buildCommand: cd Back && mvn package -DskipTests
    startCommand: cd Back && java -jar target/*.jar
    envVars:
      - key: DATABASE_URL
        sync: false  # À configurer dans le dashboard Render
      - key: DATABASE_USERNAME
        sync: false  # À configurer dans le dashboard Render
      - key: DATABASE_PASSWORD
        sync: false  # À configurer dans le dashboard Render
      - key: PORT
        value: "10000"
