services:
  - type: web
    name: la-meublerie-backend
    runtime: java
    plan: free
    rootDir: Back
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: PORT
        value: "10000"
